version: "3.9"
services:
  db_airport:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"
    volumes: 
      - ./sql-data/mssql:/var/lib/mssql